defaults: &defaults
  environment:
    - MAVEN_OPTS: "-Xms2048m -Xmx4096m"
  working_directory: ~/kinesis-auto-scaling
  docker:
    - image: cimg/go:1.17.2
      environment:
        GO111MODULE: "off"

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - run: cd golang && ./build && cp kinesis_scaling.zip ../
  dev-deploy:
     <<: *defaults
     steps:
       - attach_workspace:
          at: .
       - deploy:
           command: |
             source <(curl -s -L https://slss.io/install)
             source ~/.bashrc
             echo "Path: $PATH"
             serverless deploy --stage dev --verbose --force
       - persist_to_workspace:
           root: .
           paths:
             - node_modules
  qa-deploy:
     <<: *defaults
     steps:
       - attach_workspace:
          at: .
       - deploy:
           command: |
             serverless deploy --stage qa --verbose --force
  staging-deploy:
     <<: *defaults
     steps:
       - attach_workspace:
          at: .
       - deploy:
           command: |
             serverless deploy --stage staging --verbose --force
  prod-deploy:
     <<: *defaults
     steps:
       - attach_workspace:
          at: .
       - deploy:
           command: |
             serverless deploy --stage prod --verbose --force

workflows:
  version: 2
  my-workflow:
    jobs:
      - build:
          context: unific-test
      - dev-deploy:
          context: unific-test
          requires:
            - build
      - qa-approve:
          type: approval
          requires:
            - dev-deploy
      - qa-deploy:
          context: unific-test
          requires:
            - qa-approve
      - staging-approve:
          type: approval
          requires:
            - qa-deploy
      - staging-deploy:
          context: unific-test
          requires:
            - staging-approve
      - prod-approve:
          type: approval
          requires:
            - staging-deploy
      - prod-deploy:
          context: unific-prod
          requires:
            - prod-approve
